// Generated by scripts/sync-linkedin-feed.mjs from local-data/linkedin/.
// Keep the raw LinkedIn export out of public assets and source control.

export interface LinkedInFeedItem {
  date: string;
  kind: string;
  title: string;
  description: string;
  url: string;
}

export const linkedinFeedItems: LinkedInFeedItem[] = [
  {
    "date": "2024-12-09T05:21:00.000Z",
    "kind": "feed document",
    "title": "Document",
    "description": "",
    "url": "https://media.licdn.com/dms/document/media/v2/D4E1FAQHF2qz-ndJ9pg/feedshare-document-pdf-analyzed/B4EZOp3ZFvGYAY-/0/1733721691799?e=1780185600&v=beta&t=t2Mhro8E45Nny-08T2iMekJ-LBJXX839wJ6BVE1bWlQ"
  },
  {
    "date": "2020-05-08T13:51:00.000Z",
    "kind": "feed photo",
    "title": "Photo",
    "description": "",
    "url": "https://media.licdn.com/dms/image/v2/C4E22AQGNvbuqARNN6Q/feedshare-shrink_800/feedshare-shrink_800/0/1588945886919?e=1781136000&v=beta&t=v-QE0Z12-YejHJUVbZJOBNulwpQi38Fxo3RVYzf_91s"
  },
  {
    "date": "2020-03-30T17:31:00.000Z",
    "kind": "feed photo",
    "title": "Photo",
    "description": "",
    "url": "https://media.licdn.com/dms/image/v2/C5622AQGHxeSksTIC_w/feedshare-shrink_800/feedshare-shrink_800/0/1585589474246?e=1781136000&v=beta&t=57LVXpLxAXNA_XxivkdFv_qXXEL9Y_i0HvgKgbkfY_Y"
  },
  {
    "date": "2019-12-13T15:01:00.000Z",
    "kind": "feed photo",
    "title": "Photo",
    "description": "",
    "url": "https://media.licdn.com/dms/image/v2/C4E22AQEFvkQXmBdGMw/feedshare-shrink_800/feedshare-shrink_800/0/1576249285878?e=1781136000&v=beta&t=8QOT9FNvDA5W6k_dDYUsQNLIAG0SPfSLYHy-lpdOU84"
  },
  {
    "date": "2019-12-11T13:57:00.000Z",
    "kind": "feed photo",
    "title": "Photo",
    "description": "",
    "url": "https://media.licdn.com/dms/image/v2/C4E22AQHCSIvJTXbaAA/feedshare-shrink_800/feedshare-shrink_800/0/1576072645673?e=1781136000&v=beta&t=JNe4sjTiUgO622sHwFhfNyfITSk9NKHfg6OIV2Un7e0"
  },
  {
    "date": "2019-12-09T14:34:00.000Z",
    "kind": "feed photo",
    "title": "Photo",
    "description": "",
    "url": "https://media.licdn.com/dms/image/v2/C4E22AQHHi1mMcDpqmg/feedshare-shrink_800/feedshare-shrink_800/0/1575902047439?e=1781136000&v=beta&t=ERdM-c3x6dWqkL8V0kFZsnyhWp9TT9-FPk97wbPbKBc"
  }
];
